<?php

namespace Cdburgess\AddressingStandards\Tables;

class States
{
    use Standardizes;

    /**
     * Two-letter state and possession abbreviations (Pub 28 Appendix B).
     * Includes full state/possession names and common variants → standard code.
     * @link https://pe.usps.com/text/pub28/28apb.htm
     */
    public static function all(): array
    {
        return [
            // States
            'ALABAMA' => 'AL',
            'AL' => 'AL',
            'ALASKA' => 'AK',
            'AK' => 'AK',
            'ARIZONA' => 'AZ',
            'AZ' => 'AZ',
            'ARKANSAS' => 'AR',
            'AR' => 'AR',
            'CALIFORNIA' => 'CA',
            'CA' => 'CA',
            'COLORADO' => 'CO',
            'CO' => 'CO',
            'CONNECTICUT' => 'CT',
            'CT' => 'CT',
            'DELAWARE' => 'DE',
            'DE' => 'DE',
            'DISTRICT OF COLUMBIA' => 'DC',
            'DC' => 'DC',
            'FLORIDA' => 'FL',
            'FL' => 'FL',
            'GEORGIA' => 'GA',
            'GA' => 'GA',
            'HAWAII' => 'HI',
            'HI' => 'HI',
            'IDAHO' => 'ID',
            'ID' => 'ID',
            'ILLINOIS' => 'IL',
            'IL' => 'IL',
            'INDIANA' => 'IN',
            'IN' => 'IN',
            'IOWA' => 'IA',
            'IA' => 'IA',
            'KANSAS' => 'KS',
            'KS' => 'KS',
            'KENTUCKY' => 'KY',
            'KY' => 'KY',
            'LOUISIANA' => 'LA',
            'LA' => 'LA',
            'MAINE' => 'ME',
            'ME' => 'ME',
            'MARYLAND' => 'MD',
            'MD' => 'MD',
            'MASSACHUSETTS' => 'MA',
            'MA' => 'MA',
            'MICHIGAN' => 'MI',
            'MI' => 'MI',
            'MINNESOTA' => 'MN',
            'MN' => 'MN',
            'MISSISSIPPI' => 'MS',
            'MS' => 'MS',
            'MISSOURI' => 'MO',
            'MO' => 'MO',
            'MONTANA' => 'MT',
            'MT' => 'MT',
            'NEBRASKA' => 'NE',
            'NE' => 'NE',
            'NEVADA' => 'NV',
            'NV' => 'NV',
            'NEW HAMPSHIRE' => 'NH',
            'NH' => 'NH',
            'NEW JERSEY' => 'NJ',
            'NJ' => 'NJ',
            'NEW MEXICO' => 'NM',
            'NM' => 'NM',
            'NEW YORK' => 'NY',
            'NY' => 'NY',
            'NORTH CAROLINA' => 'NC',
            'NC' => 'NC',
            'NORTH DAKOTA' => 'ND',
            'ND' => 'ND',
            'OHIO' => 'OH',
            'OH' => 'OH',
            'OKLAHOMA' => 'OK',
            'OK' => 'OK',
            'OREGON' => 'OR',
            'OR' => 'OR',
            'PENNSYLVANIA' => 'PA',
            'PA' => 'PA',
            'RHODE ISLAND' => 'RI',
            'RI' => 'RI',
            'SOUTH CAROLINA' => 'SC',
            'SC' => 'SC',
            'SOUTH DAKOTA' => 'SD',
            'SD' => 'SD',
            'TENNESSEE' => 'TN',
            'TN' => 'TN',
            'TEXAS' => 'TX',
            'TX' => 'TX',
            'UTAH' => 'UT',
            'UT' => 'UT',
            'VERMONT' => 'VT',
            'VT' => 'VT',
            'VIRGINIA' => 'VA',
            'VA' => 'VA',
            'WASHINGTON' => 'WA',
            'WA' => 'WA',
            'WEST VIRGINIA' => 'WV',
            'WV' => 'WV',
            'WISCONSIN' => 'WI',
            'WI' => 'WI',
            'WYOMING' => 'WY',
            'WY' => 'WY',

            // Territories & Possessions
            'AMERICAN SAMOA' => 'AS',
            'AS' => 'AS',
            'GUAM' => 'GU',
            'GU' => 'GU',
            'NORTHERN MARIANA ISLANDS' => 'MP',
            'MP' => 'MP',
            'PUERTO RICO' => 'PR',
            'PR' => 'PR',
            'VIRGIN ISLANDS' => 'VI',
            'VI' => 'VI',
            'FEDERATED STATES OF MICRONESIA' => 'FM',
            'FM' => 'FM',
            'MARSHALL ISLANDS' => 'MH',
            'MH' => 'MH',
            'PALAU' => 'PW',
            'PW' => 'PW',

            // Military
            'ARMED FORCES AMERICAS' => 'AA',
            'AA' => 'AA',
            'ARMED FORCES EUROPE' => 'AE',
            'ARMED FORCES MIDDLE EAST' => 'AE',
            'ARMED FORCES CANADA' => 'AE',
            'AE' => 'AE',
            'ARMED FORCES PACIFIC' => 'AP',
            'AP' => 'AP',
        ];
    }

}